name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7 # Make sure to use the appropriate pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Build the Next.js app
        run: pnpm run build

      - name: Deploy to GitHub Pages
        run: |
          pnpm run export
          # Add deploy script or GitHub Pages deployment step here
